name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install pylint nose  # Ensure test/lint tools are installed

      - name: Run Linter
        run: |
          pylint --rcfile=.pylintrc service tests

      - name: Run Tests
        env:
          DATABASE_URI: postgresql://postgres:pgs3cr3t@postgres:5432/testdb
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=service