name: Continuous Integration

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          pylint --rcfile=.pylintrc service tests
      - name: Run tests
        env:
          DATABASE_URI: postgresql://postgres:postgres@localhost:5432/postgres
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=service